// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LeD_CustomMenu","status":false,"description":"Customize the title screen menu","parameters":{"X Position":"0","Y Position":"0","Width":"240","Height":"96","Opacity":"192"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.2) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}},
{"name":"GALV_DiagonalMovementMZ","status":true,"description":"(v.1.2) Enables player to move diagonally and characters can use diagonal charset.","parameters":{"dMouse":"true","dCharset":"false","dSpeed":"70","blockDiag":"true"}},
{"name":"GALV_CamControlMZ","status":true,"description":"(v.1.7) Allows greater control over where the game camera is focused. View documentation for plugin commands.","parameters":{"useZoom":"true","bZoom":"1"}},
{"name":"GALV_CustomTitle","status":false,"description":"(v.1.5) A plugin to allow you to modify aesthetics of the default title screen.","parameters":{"-- Command Window --":"","Cmd Width":"240","Cmd Position X":"(Graphics.boxWidth - this.width) / 2","Cmd Position Y":"Graphics.boxHeight - this.height - 96","Cmd Windowskin":"Window","Cmd Window Opacity":"255","Cmd Text Align":"left","Cmd Font Name":"","Cmd Font File":"","Cmd Font Size":"28","Cmd Color":"#ffffff","Cmd Outline Width":"4","Cmd Outline Color":"#000000","Cmd Button Size":"36","-- Title Text --":"","Title Position X":"20","Title Position Y":"Graphics.height / 4","Title Width":"Graphics.width - x * 2;","Title Text Align":"center","Title Font Name":"","Title Font File":"","Title Font Size":"72","Title Color":"#ffffff","Title Outline Width":"8","Title Outline Color":"#000000","-- Press Start --":"","Start Image":"","Start Position X":"(Graphics.boxWidth - this.pStart.width) / 2","Start Position Y":"Graphics.boxHeight - this.pStart.height - 96","Start Blinking":"5,10,10,120","Start Show Once":"false","-- Advanced --":"","Layer Graphics":"","Animated Sprites":""}}
];
